spring:
  messages:
    basename: errors
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

#    mail:
#      host: smtp.gmail.com
#      port: 587
#      username: junyeonggim5@gmail.com
#      password:
#      properties:
#        mail:
#          smtp:
#            auth: true
#            starttls:
#              enable: true







logging:
  level:
    org.hibernate.sql: debug

